# Generated by Django 6.1.1 on 2026-09-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Texte source utilisé pour la classification automatique')),
                ('autorite_contractante', models.CharField(max_length=255)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_publication', models.DateField()),
                ('date_limite', models.DateField()),
                ('statut', models.CharField(choices=[('publie', 'Publié'), ('en_cours', 'En cours'), ('attribue', 'Attribué'), ('infructueux', 'Infructueux')], default='publie', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_offre_crees', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_offre', to='appels_offres.district')),
                ('secteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_offre', to='appels_offres.secteur')),
                ('type_procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_offre', to='appels_offres.typeprocedure')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_source', models.TextField()),
                ('confiance', models.FloatField(help_text='Score de confiance du modèle (0 à 1)')),
                ('date_prediction', models.DateTimeField(auto_now_add=True)),
                ('appel_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='appels_offres.appeloffre')),
                ('secteur_predit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appels_offres.secteur')),
                ('secteur_reel', models.ForeignKey(blank=True, help_text='Rempli manuellement lors de la vérification, pour calculer les métriques du modèle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='appels_offres.secteur')),
            ],
        ),
    ]
