# Generated by Django 6.1.1 on 2026-10-09 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='date_import',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text="Date d'import dans notre base"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='mode_passation',
            field=models.CharField(blank=True, help_text='Mode de passation (ACO, AOO, AMI, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='numero_armp',
            field=models.CharField(blank=True, help_text='Numéro officiel ARMP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='reference_armp',
            field=models.CharField(blank=True, help_text="Référence officielle de l'avis ARMP", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='region',
            field=models.CharField(blank=True, help_text='Région administrative (ex : Atsimo-Andrefana)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='source',
            field=models.CharField(choices=[('DEMO', 'Données de démonstration'), ('ARMP', 'Portail ARMP')], default='DEMO', help_text='Origine de la donnée : démonstration ou portail ARMP', max_length=10),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='url_source',
            field=models.URLField(blank=True, help_text='Lien vers la fiche originale sur le site ARMP', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_offre_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='titre',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='appeloffre',
            index=models.Index(fields=['source'], name='appels_offr_source_195f46_idx'),
        ),
        migrations.AddIndex(
            model_name='appeloffre',
            index=models.Index(fields=['region'], name='appels_offr_region_16a3be_idx'),
        ),
        migrations.AddIndex(
            model_name='appeloffre',
            index=models.Index(fields=['date_limite'], name='appels_offr_date_li_c6b2e2_idx'),
        ),
    ]
