# Generated by Django 6.1.1 on 2026-10-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels_offres', '0002_appeloffre_date_import_appeloffre_mode_passation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['region__nom', 'nom']},
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='date_import',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_offre', to='appels_offres.district'),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='mode_passation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='numero_armp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='reference_armp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_offre', to='appels_offres.secteur'),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='source',
            field=models.CharField(choices=[('DEMO', 'Données de démonstration'), ('ARMP', 'Portail ARMP')], default='DEMO', max_length=10),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='type_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_offre', to='appels_offres.typeprocedure'),
        ),
        migrations.AlterField(
            model_name='appeloffre',
            name='url_source',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='classificationlog',
            name='secteur_reel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='appels_offres.secteur'),
        ),
        migrations.AlterField(
            model_name='district',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='appels_offres.region'),
        ),
    ]
